#!/usr/bin/env bash
# Export a pip lock from the active developer ``pi-dex`` conda env.
#
# Full guide: docs/inference-env.md
#
# Run on the **development** machine after the env is known-good:
#   source .../miniconda/etc/profile.d/conda.sh && conda activate pi-dex
#   bash scripts/export_inference_lock.sh
#
# Writes: configs/inference/pip-lock.txt
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${1:-${ROOT}/configs/inference/pip-lock.txt}"

if ! command -v python >/dev/null; then
  echo "python not on PATH; activate pi-dex first" >&2
  exit 1
fi

python - <<PY
from __future__ import annotations

import platform
import subprocess
import sys
from pathlib import Path

out = Path(${OUT@Q})
out.parent.mkdir(parents=True, exist_ok=True)
raw = subprocess.check_output([sys.executable, "-m", "pip", "freeze"], text=True)

skip_prefixes = ("kshift @", "openpi @", "pi-dex @", "pi_dex @", "-e ")
lines: list[str] = []
for line in raw.splitlines():
    s = line.strip()
    if not s or s.startswith("#"):
        continue
    if s.startswith(skip_prefixes):
        continue
    if " @ file://" in s or " @ /" in s:
        continue
    # Keep VCS pins; drop bare editables without URL.
    if s.startswith("-e ") and "git+" not in s:
        continue
    lines.append(s)

lines = sorted(set(lines), key=str.lower)

torch_ver = "?"
cuda = "?"
try:
    import torch

    torch_ver = torch.__version__
    cuda = str(torch.version.cuda)
except Exception:
    pass

header = [
    "# Locked from developer pi-dex conda env.",
    f"# python={sys.version.split()[0]} platform={platform.platform()}",
    f"# torch={torch_ver} cuda={cuda}",
    "# Regenerated by: bash scripts/export_inference_lock.sh",
    "# Consumed by: bash scripts/setup_inference_env.sh",
    "# Local editable packages (openpi / pi-dex / openpi-client) are installed from this repo, not this lock.",
    "",
]
out.write_text("\\n".join(header + lines) + "\\n", encoding="utf-8")
print(f"wrote {out} ({len(lines)} packages)")
print(f"torch={torch_ver} cuda={cuda}")
PY
